# Generated by Django 5.0.8 on 2024-08-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookingSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grocery', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Ingredients for recipe',
                'ordering': ['-quantity'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('servings', models.ImageField(upload_to='')),
                ('time', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='recipes_photo/')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
    ]
