# Generated by Django 5.0.8 on 2024-08-11 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipeapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.recipe'),
        ),
        migrations.AddField(
            model_name='cookingsteps',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.recipe'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeapp.recipecategory'),
        ),
    ]
